return {
	{
		"which-key.nvim",
		for_cat = "general.extra",
		-- cmd = { "" },
		event = "DeferredUIEnter",
		-- ft = "",
		-- keys = "",
		-- colorscheme = "",
		after = function(plugin)
			require("which-key").setup({})
			require("which-key").add({
				{ "<leader><leader>", group = "buffer commands" },
				{ "<leader><leader>_", hidden = true },
				{ "<leader>b", group = "[b]uffer" },
				{ "<leader>b_", hidden = true },
				{ "<leader>c", group = "[c]ode" },
				{ "<leader>c_", hidden = true },
				{ "<leader>d", group = "[d]ocument" },
				{ "<leader>d_", hidden = true },
				{ "<leader>f", group = "[f]ile/find" },
				{ "<leader>f_", hidden = true },
				{ "<leader>g", group = "[g]it" },
				{ "<leader>g_", hidden = true },
				{ "<leader>m", group = "[m]arkdown" },
				{ "<leader>m_", hidden = true },
				{ "<leader>q", group = "[q]uit/session" },
				{ "<leader>q_", hidden = true },
				{ "<leader>r", group = "[r]ename" },
				{ "<leader>r_", hidden = true },
				{ "<leader>s", group = "[s]earch" },
				{ "<leader>s_", hidden = true },
				{ "<leader>t", group = "[t]erminal/toggle" },
				{ "<leader>t_", hidden = true },
				{ "<leader>u", group = "[u]i" },
				{ "<leader>u_", hidden = true },
				{ "<leader>w", group = "[w]orkspace" },
				{ "<leader>w_", hidden = true },
				{ "<leader>x", group = "diagnostics/quickfi[x]" },
				{ "<leader>x_", hidden = true },
			})
		end,
	},
}
